spring.application.name=app
# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openai.api.key=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
huggingface.api.key=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
gemini.api.key=AIzaSyDBUXkqv-z7tpCFFk89dQfYtXAX5YTJgAI
app.jwt.secret=malayasahumalayasahumalayasahumalayasahumalayasahu2004malaya2004
